export enum EventType {
  PAGE_CHANGE = 'PAGE_CHANGE',
  ORDER_CHANGE = 'ORDER_CHANGE',
  KEYWORD_CHANGE = 'KEYWORD_CHANGE',
  COUNTRY_CHANGE = 'COUNTRY_CHANGE',
  FLAG_CHANGE = 'FLAG_CHANGE',
  ROLE_CHANGE = 'ROLE_CHANGE',
}
