export enum EventType {
  PAGE_CHANGE = 'PAGE_CHANGE',
  ORDER_CHANGE = 'ORDER_CHANGE',
  KEYWORD_CHANGE = 'KEYWORD_CHANGE',
  ROLES_CHANGE = 'ROLES_CHANGE',
  DEPTS_CHANGE = 'DEPTS_CHANGE',
  OPEN_FLAG_CHANGE = 'OPEN_FLAG_CHANGE',
}
